### ISSUE TITLE
test fail on osx

### ISSUE THREAD

**Issue by simobasso** [xrmx/pylokit#10]
```
Bootstrapping exception 

'component context fails to supply singleton com.sun.star.configuration.theDefaultProvider of type com.sun.star.lang.XMultiServiceFactory'

libc++abi.dylib: terminating with uncaught exception of type com::sun::star::uno::DeploymentException
```

**Comment by simobasso** [comment]
changing some path:

```
Terminating app due to uncaught exception 'NSGenericException',
reason: 'NSRunAlertPanel may only be invoked from the main thread. Behavior on other threads is undefined.'
```

**Comment by xrmx** [comment]
So it looks like libreofficekit is not tested upstream on not linux platforms so i don't think we can do much until it's fixed upstream.
A reference for cffi on other platforms https://github.com/Kozea/cairocffi/issues/28

**Comment by xrmx** [comment]
As we have found out LibreOfficeKit is not supported on MacOS, so we can only revisit this if it changes upstream. Closing as there's nothing actionable.
