### ISSUE TITLE
Truncated or oversized response headers received from daemon process

### ISSUE THREAD

**Issue by aliangm** [xrmx/pylokit#16]
**[wsgi:error] [pid 8216:tid 140512145114880] [client 127.0.0.1:36828] Truncated or oversized response headers received from daemon process**

This is working properly on my local env and the functionality is fine.

When I deploy the app on the server, I got the above error message.

Office('/usr/lib/libreoffice/program')

It only causes issue on this line.

Is there any solution for this?
BTW, I used this on the Django framework and I am on the apache server on Ubuntu.

**Comment by xrmx** [comment]
You should not use pylokit from your django workers, you should implement some IPC (pubsub, a queue, etc...) from your django workers to the pylokit instance.

**Comment by aliangm** [comment]
Thanks for your reply, but I can not get you.
This is working properly on the local environment.
The issue only occurs when I deployed the app to the apache server on Ubuntu.

**Comment by xrmx** [comment]
You are free to disregard my suggestions :) Just keep in mind that if it works with django runserver does not mean it's a good idea. Said that closing the issue as it's not a pylokit issue.
