### ISSUE TITLE
pylokit failed to initialize on mac Big Sur

### ISSUE THREAD

**Issue by DG007** [xrmx/pylokit#18]
I get the following error on trying to use this library on mac big sur

File "/usr/local/lib/python3.9/site-packages/pylokit/lokit.py", line 107, in __init__
    raise LoKitInitializeError("Failed to initialize LibreOfficeKit")
pylokit.lokit.LoKitInitializeError: Failed to initialize LibreOfficeKit

**Comment by xrmx** [comment]
From the first paragraph of the README "LibreOfficeKit currently works only on Linux systems."
