### ISSUE TITLE
Use lok_init function for LibreOfficeKit initialisation

### ISSUE THREAD

**Issue by dveselov** [xrmx/pylokit#9]
Hi, Riccardo!
What do you think about replacing your [python code](https://github.com/xrmx/pylokit/blob/master/pylokit/lokit.py#L100), which tries to find LO libs, with [built-in](https://github.com/LibreOffice/core/blob/932804559e845fb8ec6ac3a3b49308136a7e81e6/include/LibreOfficeKit/LibreOfficeKitInit.h#L278) `lok_init` function, that does exactly same work, but also loads shared libs for win/osx platforms?
If you're OK with it, I can write a patch.

**Comment by xrmx** [comment]
@dveselov I don't think we can do that using binding with cffi at the ABI level as we are doing now: we need need to load the shared object for wrapping its symbols. Switching to API would require to depend on compiler in order to work. Am not sure i want to add that dependency.

**Comment by dveselov** [comment]
OK, got it.
Another question: how about support unstable api methods, like [per-tile rendering](https://github.com/LibreOffice/core/blob/932804559e845fb8ec6ac3a3b49308136a7e81e6/include/LibreOfficeKit/LibreOfficeKit.h#L237) and so on?

**Comment by xrmx** [comment]
@dveselov no plan on doing the work unless someone is willing to sponsor it :) Ideally we'd have more than api definition (once per major release?) and add a way to pass it to Office.
